export const SET_USER = "SET_USER";

export const FETCH_WORKFLOWS = "FETCH_WORKFLOWS";
export const DELETE_WORKFLOW = "DELETE_WORKFLOW";
export const UPDATE_WORKFLOW = "UPDATE_WORKFLOW";
export const CREATE_WORKFLOW = "CREATE_WORKFLOW";

export const FETCH_EVENTS = "FETCH_EVENTS";
export const DELETE_EVENT = "DELETE_EVENT";
export const CREATE_EVENT = "CREATE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";

export const FETCH_ENTRANCES = "FETCH_ENTRANCES";
export const DELETE_ENTRANCE = "DELETE_ENTRANCE";
export const CREATE_ENTRANCE = "CREATE_ENTRANCE";

export const FETCH_SUBSCRIBERS = "FETCH_SUBSCRIBERS";
export const DELETE_SUBSCRIBER = "DELETE_SUBSCRIBER";
export const CREATE_SUBSCRIBER = "CREATE_SUBSCRIBER";
export const UPDATE_SUBSCRIBER = "UPDATE_SUBSCRIBER";

export const FETCH_ERROR = "FETCH_ERROR";
